### ISSUE TITLE
Render locally broken

### ISSUE THREAD

**Issue by Arau** [ondat/documentation#31]
The instructions specify that the docs can be rendered locally by creating symlinks from the documentation source towards the documentation-backend. However, hugo doesn't follow symlinks as Go's filepath.Walk doesn't follow them. Hence the softlink can't work. 

We can make changes to run rsync or copies of the files themselves for the local rendering.

**Comment by Arau** [comment]
@mdeneva  FYI

**Comment by cvlc** [comment]
Resolved via #32
